### ISSUE TITLE
About a Python3 PR

### ISSUE THREAD

**Issue by Mansarde** [R0X3/chanerator#2]
Hi @GONQ I forked your repo and created a Python3 version of it.
Are you interested in a PR for it?

If yes, then could you create a Python3 branch for me to create the PR against?
I'm just asking because of Python3's backwards-incompatibility and thought you probably would like to preserve the Python2 (master) branch.

Cheers,
Mansarde

**Comment by GONQ** [comment]
@Mansarde Branch 'python3' cloned from master. You may send the pull request at your leisure.

Blessings,
GONQ

**Comment by Mansarde** [comment]
@GONQ Ok, I've just created PR #3 for it. :)
